import { IComponent } from 'web-angularjs-component-definition/IComponent';
export declare class Definition {
    game: IComponent;
    gameCreate: IComponent;
    gameDetail: IComponent;
    gameEdit: IComponent;
    gameList: IComponent;
    gameListSingle: IComponent;
    event: IComponent;
    eventCreate: IComponent;
    eventDetail: IComponent;
    eventEdit: IComponent;
    eventList: IComponent;
    eventListSingle: IComponent;
    team: IComponent;
    teamCreate: IComponent;
    teamDetail: IComponent;
    teamEdit: IComponent;
    teamList: IComponent;
    teamListSingle: IComponent;
    player: IComponent;
    playerCreate: IComponent;
    playerDetail: IComponent;
    playerEdit: IComponent;
    playerList: IComponent;
    playerListSingle: IComponent;
    match: IComponent;
    matchCreate: IComponent;
    matchDetail: IComponent;
    matchEdit: IComponent;
    matchList: IComponent;
    matchListSingle: IComponent;
    constructor();
}
export declare let definition: Definition;
